### ISSUE TITLE
No longer functions in 2026.5.0

### ISSUE THREAD

**Issue by pantherale0** [PiotrMachowski/Home-Assistant-custom-components-Saver#57]
Hi,

FYI - this integration is no longer working in 2026.5.0

```
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 22:49:37 (1 occurrence)
Last logged: 22:49:37

Setup failed for custom integration 'saver': Unable to import component: cannot import name '_get_state_if_valid' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1024, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/saver/__init__.py", line 10, in <module>
    from homeassistant.helpers.template import _get_state_if_valid, Template, TemplateEnvironment
ImportError: cannot import name '_get_state_if_valid' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1044, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1036, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/saver/__init__.py", line 10, in <module>
    from homeassistant.helpers.template import _get_state_if_valid, Template, TemplateEnvironment
ImportError: cannot import name '_get_state_if_valid' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
```

This function has been moved:

https://github.com/home-assistant/core/pull/167996/changes#diff-80db65e115f5f2608dfc5392024b8cf9ac32f1589249bb48c07dfeee98cd53eaR483
Related: https://github.com/home-assistant/core/pull/167996

**Comment by PiotrMachowski** [comment]
Thank you for the info!

**Comment by pantherale0** [comment]
No problem - I'd submit a PR, but pretty busy with some other bits at the moment

**Comment by PiotrMachowski** [comment]
There's a big change waiting on the dev branch, I'll add the fix for this problem as well and test it on the latest beta

**Comment by HaraldGithub** [comment]
> I'll add the fix for this problem as well and test it on the latest beta

Will this fix be ready for the release of ha 2026.5.0 tomorrow?

**Comment by PiotrMachowski** [comment]
Yes, it will. It's already on the dev branch, I'm just doing some refactoring as well

**Comment by PiotrMachowski** [comment]
Fixed in [v3.0.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver/releases/tag/v3.0.0)
